In [7]:
from mxnet import nd

从MXNet 导入ndarray模块。这里nd是ndarray的缩写形式

In [8]:
x = nd.arange(12)
x



[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
<NDArray 12 @cpu(0)>

用arange函数创建一个行向量

返回了一个NDArray实例，其中包含了从0开始的12个连续整数。
从打印x时显示的属性<NDArray 12 @cpu(0)> 可以看出，它是长度为12的一维数组，且被创建在cpu使用的内存上。
其中"@cpu(0)"里的0没有特别的意义，并不代表特定的核。

In [9]:
x.shape


(12,)

我们可以通过shape属性来获取NDArray实例的形状

In [10]:
x.size

12

我们也可以通过size属性得到NDArray实例中元素的总数

下面使用reshape函数把行向量x的形状改为(3,4),也就是一个3行4列的矩阵，并记作X,.除了形状改变之外，X中的元素保持不变。。

In [11]:
X = x.reshape((3,4))

In [12]:
X



[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

注意X属性中的形状发生了变化。上面X.reshape((3,4))也可以写成X.reshape((-1,4))或X.reshape((3,-1))。由于X的元素个数是已知的，这里的-1是能够通过元素个数和其他唯独的大小推断出来的。

接下来，我们创建一个各元素为0，形状为（2，3，4） 的张量。实际上，之前创建的向量和矩阵都是特殊的张量。

In [14]:
nd.zeros((2,3,4))


[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<NDArray 2x3x4 @cpu(0)>

类似的，我么可以创建各元素为1 的张量

In [15]:
nd.ones((3,4))


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
<NDArray 3x4 @cpu(0)>

我们也可以通过python的列表(list)指定需要创建的NDArray总每一元素的值

In [16]:
Y = nd.array([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

In [17]:
Y



[[2. 1. 4. 3.]
 [1. 2. 3. 4.]
 [4. 3. 2. 1.]]
<NDArray 3x4 @cpu(0)>

In [18]:
YDemo = nd.array([1,2,3,4])
YDemo



[1. 2. 3. 4.]
<NDArray 4 @cpu(0)>

有些情况下，我们需要随机生成NDArray中每个元素的值。下面我们创建一个形状为(3,4)的NDArray。它的每个元素都随机采样于均值为0、标准差为1的正态分布。


In [19]:
nd.random.normal(0,1,shape=(3,4))


[[ 1.1630787   0.4838046   0.29956347  0.15302546]
 [-1.1688148   1.5580711  -0.5459446  -2.3556297 ]
 [ 0.5414402   2.6785066   1.2546344  -0.54877394]]
<NDArray 3x4 @cpu(0)>

## 运算

NDArray支持大量的运算符。例如，我们可以对之前创建的两个形状为(3,4)的NDArray做暗元素加法

In [20]:
X + Y


[[ 2.  2.  6.  6.]
 [ 5.  7.  9. 11.]
 [12. 12. 12. 12.]]
<NDArray 3x4 @cpu(0)>

In [21]:
X * Y


[[ 0.  1.  8.  9.]
 [ 4. 10. 18. 28.]
 [32. 27. 20. 11.]]
<NDArray 3x4 @cpu(0)>

In [22]:
X / Y



[[ 0.    1.    0.5   1.  ]
 [ 4.    2.5   2.    1.75]
 [ 2.    3.    5.   11.  ]]
<NDArray 3x4 @cpu(0)>

In [23]:
Y.exp()


[[ 7.389056   2.7182817 54.59815   20.085537 ]
 [ 2.7182817  7.389056  20.085537  54.59815  ]
 [54.59815   20.085537   7.389056   2.7182817]]
<NDArray 3x4 @cpu(0)>

除了按元素计算外，我们还可以使用dot函数做矩阵乘法，下面将X 与Y 的专职做矩阵乘法。由于X 是3行4列的矩阵，Y转置为4行3列的矩阵，因此两个矩阵相乘得到3行3列的矩阵。

In [24]:
nd.dot(X, Y.T)


[[ 18.  20.  10.]
 [ 58.  60.  50.]
 [ 98. 100.  90.]]
<NDArray 3x3 @cpu(0)>

我们也可以将多个NDArray连结。下面分别在行上和列上连结两个矩阵，可以看到，输出的第一个NDArray在维度0的长度为两个输入矩阵在维度0 的长度之和，而输出的第二个NDArray在维度1的长度为两个输入矩阵在维度1的长度之和

In [25]:
nd.concat(X, Y, dim = 0), nd.concat(X, Y, dim = 1)

(
 [[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]
  [ 2.  1.  4.  3.]
  [ 1.  2.  3.  4.]
  [ 4.  3.  2.  1.]]
 <NDArray 6x4 @cpu(0)>, 
 [[ 0.  1.  2.  3.  2.  1.  4.  3.]
  [ 4.  5.  6.  7.  1.  2.  3.  4.]
  [ 8.  9. 10. 11.  4.  3.  2.  1.]]
 <NDArray 3x8 @cpu(0)>)

使用条件判断式可以得到元素为0或1的新的NDArray。以X == Y 为例，如果X和Y在相同位置的条件判断为真，那么新的NDarray在相同位置的值为1， 反之为0

In [26]:
X == Y


[[0. 1. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
<NDArray 3x4 @cpu(0)>

对NDArray中的所有元素求和得到只有一个元素的NDArray

In [27]:
X.sum()


[66.]
<NDArray 1 @cpu(0)>

我们可以通过asscalar函数将结果变换为python中的标量。下面例子中X的l2范数结果同上例一样是单元素NDArray，但最后结果变换成了python中的标量  

In [30]:
X.norm().asscalar()

22.494442

## 广播机制

前面我们看到如何对两个形状相同的NDArray做按元素运算。当对两个形状不同的NDArray按元素运算时，可能会触发广播机制；先适当复制元素使这两个NDArray形状相同后再按元素运算。

In [31]:
A = nd.arange(3).reshape((3,1))
B = nd.arange(2).reshape((1,2))
A,B


(
 [[0.]
  [1.]
  [2.]]
 <NDArray 3x1 @cpu(0)>, 
 [[0. 1.]]
 <NDArray 1x2 @cpu(0)>)

由于A 和B分别是3行1列和1行2列的矩阵，如果要计算A+B，那么A重第一列的3个元素被广播到了第二列而B重第一行的2个元素被广播到了第二行和第三行。
如此，就可以对2个3行2列的矩阵按元素相加

In [33]:
A + B


[[0. 1.]
 [1. 2.]
 [2. 3.]]
<NDArray 3x2 @cpu(0)>

## 索引


在NDArray中，索引代表了元素的位置。NDArray的索引从0开始逐一增加。例如，一个3行2列
的矩阵的行索引分别为0.1和2，列索引分别为0和1

在下面的例子中，我们制定了NDArray的行索引截取范围[1:3].依据左闭右开制定范围的管理，它截取了矩阵X中航索引为1和2的两行

In [34]:
X[1:3]


[[ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 2x4 @cpu(0)>

我们可以制定NDArray中需要访问的单个元素的位置，如矩阵中行和列的索引，并未该元素重新赋值

In [35]:
X[1,2] = 9
X



[[ 0.  1.  2.  3.]
 [ 4.  5.  9.  7.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

当然，我们也可以截取一部分元素，并未他们重新赋值。在下面的例子中，我们为行索引为1的每一列元素重新赋值。

In [36]:
X[1:2, :] = 12
X


[[ 0.  1.  2.  3.]
 [12. 12. 12. 12.]
 [ 8.  9. 10. 11.]]
<NDArray 3x4 @cpu(0)>

In [37]:
X[:, 1:2] = 0
X



[[ 0.  0.  2.  3.]
 [12.  0. 12. 12.]
 [ 8.  0. 10. 11.]]
<NDArray 3x4 @cpu(0)>

## 运算的内存开销

在前面的例子里我们对每个操作新开内存来存储运算结果。举个例子，即使像Y = X + Y 这样的运算，我们也会新开内存，然后将Y指向新内存，为了掩饰这一点，我们可以使用python自带的id函数：如果两个实例的ID一致，那么他们所对应的内存地址相同；反之则不同

In [38]:
before = id(Y)
Y = Y + X
id(Y) == before

False

如果想制定结果到特定内存，我们可以使用前面介绍额索引来进行替换操作。在下面的例子中，我们先通过zeros_like创建和Y形状相同且元素为0的NDArray，记为Z。接下来，我们把X+ Y的结果通过[:] 写进Z对应的内存中

In [40]:
Z = Y.zeros_like()
before = id(Z)
Z[:] = X + Y
id(Z) == before

True

实际上，上例中我们还是为X + Y开了临时内存来存储计算结果，在复制到Z对应的内存。如果想避免这个临时内存开销，我们可以使用运算符全名函数中的out参数

In [41]:
nd.elemwise_add(X, Y, out = Z)


[[ 2.  1.  8.  9.]
 [25.  2. 27. 28.]
 [20.  3. 22. 23.]]
<NDArray 3x4 @cpu(0)>

In [42]:
id(Z) == before

True

如果X的值在之后的程序中不会复用，我们也可以用X[:] = X + Y 或者 X += Y 来减少运算的内存开销

In [43]:
before = id(X)
X += Y
id(X) == before

True

## NDArray和Numpy相互转换

我们可以通过array函数和asnumpy函数领数据在NDArray和Numpy格式相互变换。下面将Numpy实例变换成NDArray实例


In [44]:
import numpy as np

P = np.ones((2,3))
D = nd.array(P)
D


[[1. 1. 1.]
 [1. 1. 1.]]
<NDArray 2x3 @cpu(0)>

In [45]:
D.asnumpy()

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

## 小结

NDArray是MXNet中存储和变换数据的主要工具
可以轻松地对NDArray创建、运算、指定索引，并与Numpy之间相互变换