## 广播


In [1]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8,135,99.0,0.9]])
A

array([[ 56. ,   0. ,   4.4,  68. ],
       [  1.2, 104. ,  52. ,   8. ],
       [  1.8, 135. ,  99. ,   0.9]])

In [2]:
cal = A.sum(axis = 0) # axis=0表示在列上进行操作     axis = 1 表示在行上进行操作
cal

array([ 59. , 239. , 155.4,  76.9])

In [11]:
percentage = 100 *A/cal.reshape(1, 4)
print((percentage))

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


练习

In [12]:
cal2 = A.sum(axis = 1)
cal2

array([128.4, 165.2, 236.7])

In [15]:
cal2.shape

(3,)

In [16]:
cal2.reshape((1,3))

array([[128.4, 165.2, 236.7]])

In [17]:
cal

array([ 59. , 239. , 155.4,  76.9])

In [18]:
cal2.shape

(3,)

In [19]:
cal2.reshape((3,1))

array([[128.4],
       [165.2],
       [236.7]])